//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sinistro
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvisoSinistro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvisoSinistro()
        {
            this.TB_PreAvisoProcessadoCobertura = new HashSet<PreAvisoProcessadoCobertura>();
            this.CoberturaSinistro = new HashSet<CoberturaSinistro>();
            this.SinistroCartaEnvio = new HashSet<SinistroCartaEnvio>();
        }
    
        public int cdaviso { get; set; }
        public short cdrefmon { get; set; }
        public int cdpes { get; set; }
        public Nullable<int> cdcausa { get; set; }
        public int cdconseg { get; set; }
        public Nullable<decimal> nrapolice { get; set; }
        public Nullable<int> nroficial { get; set; }
        public Nullable<int> nravisoramo { get; set; }
        public System.DateTime dtaviso { get; set; }
        public System.DateTime dtsin { get; set; }
        public System.DateTime dtlib { get; set; }
        public System.DateTime dtencerr { get; set; }
        public System.DateTime dtreab { get; set; }
        public System.DateTime dtemi { get; set; }
        public System.DateTime dtpago { get; set; }
        public System.DateTime dtcanc { get; set; }
        public decimal vltotsinistro { get; set; }
        public decimal vlpagsin { get; set; }
        public decimal vldesp { get; set; }
        public decimal vlsalv { get; set; }
        public decimal vlress { get; set; }
        public short stsituacao { get; set; }
        public int cdemi { get; set; }
        public System.DateTime dtatu { get; set; }
        public string indres { get; set; }
        public Nullable<int> cdprodsin { get; set; }
        public string incossaceito { get; set; }
        public string obs { get; set; }
        public string localsinistro { get; set; }
        public Nullable<int> nrsinlider { get; set; }
        public Nullable<System.DateTime> dtgeracao { get; set; }
        public string inacaojud { get; set; }
        public string incorrmonet { get; set; }
        public Nullable<System.DateTime> dtcorrmonet { get; set; }
        public Nullable<System.DateTime> dtultcorrmonet { get; set; }
        public Nullable<short> tpcond { get; set; }
        public Nullable<int> cdcidade { get; set; }
        public string cdaut { get; set; }
        public Nullable<decimal> nrcgccpf { get; set; }
        public string nmben { get; set; }
        public string inimpressaoetq { get; set; }
        public Nullable<System.DateTime> dtnotif { get; set; }
        public string cd_doe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAvisoProcessadoCobertura> TB_PreAvisoProcessadoCobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoberturaSinistro> CoberturaSinistro { get; set; }
        public virtual CausaSinistro CausaSinistro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinistroCartaEnvio> SinistroCartaEnvio { get; set; }
    }
}
