//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sinistro
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvisoSinCes
    {
        public int cdaviso { get; set; }
        public int cdpesseg { get; set; }
        public short cdrefmon { get; set; }
        public int cdconseg { get; set; }
        public int cdemi { get; set; }
        public short tpces { get; set; }
        public string tppcd { get; set; }
        public int nrordces { get; set; }
        public int nrapo { get; set; }
        public short tpaviso { get; set; }
        public System.DateTime dtatu { get; set; }
        public System.DateTime dtindeniz { get; set; }
        public System.DateTime dtreceb { get; set; }
        public System.DateTime dtress { get; set; }
        public System.DateTime dtsalv { get; set; }
        public decimal vltotpago { get; set; }
        public decimal vltotdesp { get; set; }
        public decimal vltotindeniz { get; set; }
        public decimal vltotsalv { get; set; }
        public decimal vltotress { get; set; }
        public short stsituacao { get; set; }
        public string obs { get; set; }
        public Nullable<System.DateTime> dtreab { get; set; }
        public Nullable<System.DateTime> dtcanc { get; set; }
        public Nullable<System.DateTime> dtemi { get; set; }
        public Nullable<System.DateTime> dtencerr { get; set; }
        public Nullable<decimal> pcporcentagem { get; set; }
        public Nullable<decimal> vltotrec { get; set; }
        public decimal pcfrqsin { get; set; }
        public Nullable<decimal> vlfrqsin { get; set; }
    }
}
