//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sinistro
{
    using System;
    using System.Collections.Generic;
    
    public partial class CausaSinistro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CausaSinistro()
        {
            this.AvisoSinistro = new HashSet<AvisoSinistro>();
        }
    
        public int cdcausa { get; set; }
        public string nmcausa { get; set; }
        public short stsituacao { get; set; }
        public System.DateTime dtatu { get; set; }
        public string inperdatot { get; set; }
        public short cdpontos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvisoSinistro> AvisoSinistro { get; set; }
    }
}
