//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sinistro
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndenizacaoSinistro
    {
        public int cdaviso { get; set; }
        public short cdcobsin { get; set; }
        public int cdpes { get; set; }
        public short cdindeniz { get; set; }
        public short cdramo { get; set; }
        public short cdsubram { get; set; }
        public string cdusuari { get; set; }
        public short cdrefmon { get; set; }
        public System.DateTime dtgeracao { get; set; }
        public System.DateTime dtliber { get; set; }
        public System.DateTime dtatu { get; set; }
        public decimal pcpartic { get; set; }
        public short qtparc { get; set; }
        public short stsituacao { get; set; }
        public decimal vlindeniz { get; set; }
        public decimal vlpago { get; set; }
        public string obs { get; set; }
        public Nullable<short> qtdias { get; set; }
        public Nullable<System.DateTime> dtref { get; set; }
        public Nullable<short> cdbcodeb { get; set; }
        public Nullable<short> cdbco { get; set; }
        public Nullable<int> cdagn { get; set; }
        public string nrctaccr { get; set; }
        public short tpcreddocpg { get; set; }
        public string dgtagn { get; set; }
        public string dgtctaccr { get; set; }
        public string obs2 { get; set; }
        public Nullable<int> cdoperacao { get; set; }
        public string inbencon { get; set; }
        public Nullable<int> qtparbencon { get; set; }
        public Nullable<int> cdpesrepass { get; set; }
        public string inrepass { get; set; }
        public Nullable<short> cdrefmonben { get; set; }
    
        public virtual CoberturaSinistro CoberturaSinistro { get; set; }
    }
}
