//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sinistro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParcelaSinistro
    {
        public int cdaviso { get; set; }
        public short cdcobsin { get; set; }
        public short cdindeniz { get; set; }
        public int cdpes { get; set; }
        public short cdparsin { get; set; }
        public short cdrefmon { get; set; }
        public System.DateTime dtger { get; set; }
        public System.DateTime dtven { get; set; }
        public System.DateTime dtpagto { get; set; }
        public System.DateTime dtatu { get; set; }
        public short stparcela { get; set; }
        public decimal vlparc { get; set; }
        public Nullable<decimal> vlcorrbencon { get; set; }
    }
}
