//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sinistro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreAvisoProcessadoCobertura
    {
        public int cd_preavicob { get; set; }
        public Nullable<int> cd_preavicer { get; set; }
        public Nullable<int> cd_ctt { get; set; }
        public Nullable<int> cd_itmsgr { get; set; }
        public Nullable<int> nr_cer { get; set; }
        public Nullable<short> cd_pdt { get; set; }
        public Nullable<short> cd_cob { get; set; }
        public Nullable<short> cd_movcob { get; set; }
        public Nullable<int> cd_avi { get; set; }
    
        public virtual AvisoSinistro AvisoSinistro { get; set; }
        public virtual PreAvisoProcessadoCertificado TB_PreAvisoProcessadoCertificado { get; set; }
    }
}
