//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sinistro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreAvisoHistorico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreAvisoHistorico()
        {
            this.TB_PreAvisoAnalise = new HashSet<PreAvisoAnalise>();
            this.TB_PreAvisoHistoricoCancelamento = new HashSet<PreAvisoHistoricoCancelamento>();
            this.TB_PreAvisoHistoricoCartaComunicacao = new HashSet<PreAvisoHistoricoCartaComunicacao>();
            this.TB_PreAvisoHistoricoJson = new HashSet<PreAvisoHistoricoJson>();
            this.TB_PreAvisoProcessadoCertificado = new HashSet<PreAvisoProcessadoCertificado>();
        }
    
        public int cd_preavihis { get; set; }
        public Nullable<int> cd_preavi { get; set; }
        public Nullable<short> tp_mov { get; set; }
        public Nullable<System.DateTime> dt_icl { get; set; }
        public string cd_usu { get; set; }
    
        public virtual PreAviso TB_PreAviso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAvisoAnalise> TB_PreAvisoAnalise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAvisoHistoricoCancelamento> TB_PreAvisoHistoricoCancelamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAvisoHistoricoCartaComunicacao> TB_PreAvisoHistoricoCartaComunicacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAvisoHistoricoJson> TB_PreAvisoHistoricoJson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAvisoProcessadoCertificado> TB_PreAvisoProcessadoCertificado { get; set; }
    }
}
