//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sinistro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreAviso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreAviso()
        {
            this.TB_PreAvisoDetalhe = new HashSet<PreAvisoDetalhe>();
            this.TB_PreAvisoHistorico = new HashSet<PreAvisoHistorico>();
        }
    
        public int cd_preavi { get; set; }
        public Nullable<short> tp_orgpdr { get; set; }
        public Nullable<int> cd_orgpdr { get; set; }
        public Nullable<short> cd_sit { get; set; }
        public string cd_ori { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAvisoDetalhe> TB_PreAvisoDetalhe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAvisoHistorico> TB_PreAvisoHistorico { get; set; }
    }
}
