//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sinistro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreAvisoCampo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreAvisoCampo()
        {
            this.TB_PreAvisoAnalise = new HashSet<PreAvisoAnalise>();
            this.TB_PreAvisoDetalhe = new HashSet<PreAvisoDetalhe>();
        }
    
        public int cd_cam { get; set; }
        public string nm_cam { get; set; }
        public string ds_cam { get; set; }
        public Nullable<int> nr_ord { get; set; }
        public Nullable<int> st_sit { get; set; }
        public Nullable<int> cd_tip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAvisoAnalise> TB_PreAvisoAnalise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAvisoDetalhe> TB_PreAvisoDetalhe { get; set; }
    }
}
