//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sinistro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinistroEntities : DbContext
    {
        public SinistroEntities()
            : base("name=SinistroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvisoSinCes> AvisoSinCes { get; set; }
        public virtual DbSet<AvisoSinistro> AvisoSinistro { get; set; }
        public virtual DbSet<CausaSinistro> CausaSinistro { get; set; }
        public virtual DbSet<CoberturaSinistro> CoberturaSinistro { get; set; }
        public virtual DbSet<IndenizacaoSinistro> IndenizacaoSinistro { get; set; }
        public virtual DbSet<ParcelaSinistro> ParcelaSinistro { get; set; }
        public virtual DbSet<SinistroCartaEnvio> SinistroCartaEnvio { get; set; }
        public virtual DbSet<PreAviso> TB_PreAviso { get; set; }
        public virtual DbSet<PreAvisoAnalise> TB_PreAvisoAnalise { get; set; }
        public virtual DbSet<PreAvisoDetalhe> TB_PreAvisoDetalhe { get; set; }
        public virtual DbSet<PreAvisoHistorico> TB_PreAvisoHistorico { get; set; }
        public virtual DbSet<PreAvisoHistoricoCancelamento> TB_PreAvisoHistoricoCancelamento { get; set; }
        public virtual DbSet<PreAvisoHistoricoCartaComunicacao> TB_PreAvisoHistoricoCartaComunicacao { get; set; }
        public virtual DbSet<PreAvisoHistoricoJson> TB_PreAvisoHistoricoJson { get; set; }
        public virtual DbSet<PreAvisoProcessadoCertificado> TB_PreAvisoProcessadoCertificado { get; set; }
        public virtual DbSet<PreAvisoProcessadoCobertura> TB_PreAvisoProcessadoCobertura { get; set; }
        public virtual DbSet<TB_Temp1> TB_Temp1 { get; set; }
        public virtual DbSet<PreAvisoCampo> TB_PreAvisoCampo { get; set; }
    }
}
