//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sinistro
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinistroCartaEnvio
    {
        public int cdcartaenvio { get; set; }
        public int cdaviso { get; set; }
        public short tpcarta { get; set; }
        public System.DateTime dtenvio { get; set; }
        public Nullable<System.DateTime> dtreceb { get; set; }
        public short streceb { get; set; }
        public System.DateTime dtcad { get; set; }
        public string cdusuari { get; set; }
    
        public virtual AvisoSinistro AvisoSinistro { get; set; }
    }
}
