//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobertura
    {
        public short cdcobert { get; set; }
        public string nmcobert { get; set; }
        public string nmacober { get; set; }
        public short cdcobsus { get; set; }
        public short cdramosg { get; set; }
        public short cdsubram { get; set; }
        public short cdagrupc { get; set; }
        public System.DateTime dtatuali { get; set; }
        public string indiarias { get; set; }
        public string inbeneficio { get; set; }
        public Nullable<decimal> vlbeneficio { get; set; }
        public Nullable<short> nrmaxparc { get; set; }
        public string infuneral { get; set; }
        public Nullable<short> cdclascob { get; set; }
        public string incobtit { get; set; }
        public string incobcon { get; set; }
        public string incobagr { get; set; }
        public string incobfil { get; set; }
        public Nullable<short> tpdoe { get; set; }
    }
}
