//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sies
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemOutRiscPess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemOutRiscPess()
        {
            this.ItemOutRiscPess1 = new HashSet<ItemOutRiscPess>();
        }
    
        public int cdconseg { get; set; }
        public int cditeseg { get; set; }
        public int nrmat { get; set; }
        public System.DateTime dtadoemp { get; set; }
        public short stsgr { get; set; }
        public System.DateTime dtsitseg { get; set; }
        public short tpmtvcan { get; set; }
        public decimal vlsal { get; set; }
        public short nrfil { get; set; }
        public int nrdpt { get; set; }
        public string inortseg { get; set; }
        public int nrcnsreg { get; set; }
        public short tpprf { get; set; }
        public string inenqaut { get; set; }
        public Nullable<short> cdprodut { get; set; }
        public Nullable<short> nrseqplnind { get; set; }
        public Nullable<int> cdagr { get; set; }
        public Nullable<int> cdpes { get; set; }
        public string insegprin { get; set; }
        public Nullable<short> tpsegagr { get; set; }
        public Nullable<System.DateTime> dtinivig { get; set; }
        public Nullable<decimal> nrcgccpf { get; set; }
        public Nullable<short> tpsex { get; set; }
        public Nullable<short> qtdias { get; set; }
        public Nullable<int> cdconsegagr { get; set; }
        public Nullable<int> cditesegagr { get; set; }
        public Nullable<int> cdsegvid { get; set; }
        public Nullable<short> tpprofseg { get; set; }
        public Nullable<int> nrppscor { get; set; }
        public Nullable<int> cdpescolcer { get; set; }
        public string inconj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemOutRiscPess> ItemOutRiscPess1 { get; set; }
        public virtual ItemOutRiscPess ItemOutRiscPess2 { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
