//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sies
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgaoProdutor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrgaoProdutor()
        {
            this.OrgaoProdutor1 = new HashSet<OrgaoProdutor>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int cdorgprt { get; set; }
        public short tporgprt { get; set; }
        public string nmorgprt { get; set; }
        public short cdrgisus { get; set; }
        public short storgprt { get; set; }
        public Nullable<int> cdorgprtvin { get; set; }
        public Nullable<short> tporgprtvin { get; set; }
        public Nullable<int> cdpes { get; set; }
        public Nullable<short> nrseqend { get; set; }
        public Nullable<int> cdpescol { get; set; }
        public Nullable<System.DateTime> dtcad { get; set; }
        public Nullable<decimal> nrcgcorgprt { get; set; }
        public Nullable<decimal> pcisspj { get; set; }
        public Nullable<int> cdcencus { get; set; }
        public Nullable<decimal> pcisspf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgaoProdutor> OrgaoProdutor1 { get; set; }
        public virtual OrgaoProdutor OrgaoProdutor2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
