//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sies
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParcelaPremio
    {
        public int cdconseg { get; set; }
        public int cdemi { get; set; }
        public short cdparpre { get; set; }
        public System.DateTime dtven { get; set; }
        public System.DateTime dtrcd { get; set; }
        public System.DateTime dtbxapar { get; set; }
        public string indocpgtgrd { get; set; }
        public string inbxafrc { get; set; }
        public short tplqdparpre { get; set; }
        public decimal vlrcd { get; set; }
        public decimal vlcomcosactp { get; set; }
        public System.DateTime dtvenprg { get; set; }
        public decimal vlvenprg { get; set; }
        public System.DateTime dtcrtcba { get; set; }
        public System.DateTime dtcbajud { get; set; }
        public System.DateTime dtcan { get; set; }
        public short stparpre { get; set; }
        public short cdrefmon { get; set; }
        public Nullable<int> cdconsegeds { get; set; }
        public Nullable<int> cdemieds { get; set; }
        public System.DateTime dtcvsrefmon { get; set; }
        public short tprcrrtt { get; set; }
        public decimal vlpretar { get; set; }
        public decimal vldesdtc { get; set; }
        public decimal vlagvdtc { get; set; }
        public decimal vlpreliq { get; set; }
        public decimal vljur { get; set; }
        public decimal vlpdapre { get; set; }
        public decimal vlcstapo { get; set; }
        public decimal vlcstvst { get; set; }
        public decimal vldesfin { get; set; }
        public decimal vliof { get; set; }
        public decimal vlpretot { get; set; }
        public decimal nrnosnum { get; set; }
        public System.DateTime dtpcsbxa { get; set; }
        public Nullable<int> tpmov { get; set; }
        public Nullable<System.DateTime> dtatu { get; set; }
        public Nullable<int> cdpesbco { get; set; }
        public Nullable<int> cdagn { get; set; }
        public string dgtagn { get; set; }
        public string nrcntcrr { get; set; }
        public string dgtctaccr { get; set; }
    }
}
