//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Sies
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SiesEntities : DbContext
    {
        public SiesEntities()
            : base("name=SiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_temp2> TB_temp2 { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<OrgaoProdutor> OrgaoProdutor { get; set; }
        public virtual DbSet<DominioCampo> TB_DOMINIO_CAMPO { get; set; }
        public virtual DbSet<Certificado> Certificado { get; set; }
        public virtual DbSet<Cobertura> Cobertura { get; set; }
        public virtual DbSet<Emissao> Emissao { get; set; }
        public virtual DbSet<ItemOutRiscPess> ItemOutRiscPess { get; set; }
        public virtual DbSet<ParcelaPremio> ParcelaPremio { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
    
        public virtual ObjectResult<PR_Login_Result> PR_Login(string cdusuari, string cdsnhsis)
        {
            var cdusuariParameter = cdusuari != null ?
                new ObjectParameter("cdusuari", cdusuari) :
                new ObjectParameter("cdusuari", typeof(string));
    
            var cdsnhsisParameter = cdsnhsis != null ?
                new ObjectParameter("cdsnhsis", cdsnhsis) :
                new ObjectParameter("cdsnhsis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_Login_Result>("PR_Login", cdusuariParameter, cdsnhsisParameter);
        }
    
        public virtual ObjectResult<PR_ValidarPermissaoMenu_Result> PR_ValidarPermissaoMenu(string cdmodsis, string cdusuari)
        {
            var cdmodsisParameter = cdmodsis != null ?
                new ObjectParameter("cdmodsis", cdmodsis) :
                new ObjectParameter("cdmodsis", typeof(string));
    
            var cdusuariParameter = cdusuari != null ?
                new ObjectParameter("cdusuari", cdusuari) :
                new ObjectParameter("cdusuari", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ValidarPermissaoMenu_Result>("PR_ValidarPermissaoMenu", cdmodsisParameter, cdusuariParameter);
        }
    
        public virtual ObjectResult<PR_ValidaAlcada_Result> PR_ValidaAlcada(string p_cdusuari, string p_cdmodsis, string p_cdprosis)
        {
            var p_cdusuariParameter = p_cdusuari != null ?
                new ObjectParameter("p_cdusuari", p_cdusuari) :
                new ObjectParameter("p_cdusuari", typeof(string));
    
            var p_cdmodsisParameter = p_cdmodsis != null ?
                new ObjectParameter("p_cdmodsis", p_cdmodsis) :
                new ObjectParameter("p_cdmodsis", typeof(string));
    
            var p_cdprosisParameter = p_cdprosis != null ?
                new ObjectParameter("p_cdprosis", p_cdprosis) :
                new ObjectParameter("p_cdprosis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ValidaAlcada_Result>("PR_ValidaAlcada", p_cdusuariParameter, p_cdmodsisParameter, p_cdprosisParameter);
        }
    }
}
