//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaf.VOL.Financeiro
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovtoSinistro
    {
        public int nrmovsin { get; set; }
        public short stsituacao { get; set; }
        public System.DateTime dtatu { get; set; }
        public System.DateTime dtlancto { get; set; }
        public System.DateTime dtctb { get; set; }
        public System.DateTime dtgeracao { get; set; }
        public System.DateTime dtrefmonet { get; set; }
        public decimal vlsinist { get; set; }
        public Nullable<int> cdoperacao { get; set; }
        public int cdaviso { get; set; }
        public Nullable<short> cdcobsin { get; set; }
        public Nullable<short> cdindeniz { get; set; }
        public int cdpes { get; set; }
        public Nullable<short> cdparsin { get; set; }
        public Nullable<short> tpaviso { get; set; }
        public short cdrefmon { get; set; }
        public System.DateTime dtvenc { get; set; }
        public short tpmovto { get; set; }
        public short tppagrec { get; set; }
        public Nullable<int> nrlancto { get; set; }
        public System.DateTime dtpcsbxa { get; set; }
        public string cdusuari { get; set; }
        public Nullable<int> cdcausa { get; set; }
        public Nullable<System.DateTime> dtaviso { get; set; }
        public string cd_doe { get; set; }
    }
}
